import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import "./globals.css";
import Navbar from "@/components/navbar";

const nunito = Nunito({
  subsets: ["latin", "vietnamese"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${nunito.variable} antialiased dark:bg-gray-900`}>
        <ThemeInit />
        <Navbar />
        <div className="flex w-full flex-col gap-4 px-4 pt-6 sm:px-6 sm:pt-10 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
